swagger: '2.0'
info:
  title: Weather Provider API
  version: 1.0.0
  x-ibm-name: weather-provider-api
host: $(catalog.host)
schemes: 
  - https
basePath: /
produces: 
  - application/json
paths:
  /current:
    get:
      summary: Current Weather
      parameters: 
        - name: zipcode
          in: query
          description: Un código postal de 5 dígitos de Estados Unidos válido
          required: true
          type: string
      responses:
        '200':
          description: Correcto
          schema:
            $ref: '#/definitions/Current'
  /today:
    get:
      summary: "Today's Weather"
      parameters: 
        - name: zipcode
          in: query
          description: Un código postal de 5 dígitos de Estados Unidos válido
          required: true
          type: string
      responses:
        '200':
          description: Información de perfil para un usuario
          schema:
            $ref: '#/definitions/Today'
definitions:
  Today:
    type: object
    properties:
      zip:
        type: string
      hi:
        type: integer
      lo:
        type: integer
      nightHumidity:
        type: integer
      city:
        type: string
      state:
        type: string
      dayHumidity:
        type: integer
  Current:
    type: object
    properties:
      zip:
        type: string
      temperature:
        type: integer
      humidity:
        type: integer
      city:
        type: string
      state:
        type: string
x-ibm-configuration:
  enforced: true
  testable: true
  phase: realized
  cors:
    enabled: true
  assembly:
    execute: 
      - operation-switch:
          title: operation-switch
          case: 
            - operations: 
                - verb: get
                  path: /current
              execute: 
                - invoke:
                    title: invoke-current
                    timeout: 60
                    verb: GET
                    cache-response: protocol
                    cache-ttl: 900
                    stop-on-error: 
                      - null
                    version: 1.0.0
                    target-url: 'https://myweatherprovider.mybluemix.net/current?zipcode={zipcode}'
            - operations: 
                - verb: get
                  path: /today
              execute: 
                - invoke:
                    title: invoke-today
                    timeout: 60
                    verb: GET
                    cache-response: protocol
                    cache-ttl: 900
                    stop-on-error: 
                      - null
                    version: 1.0.0
                    description: ''
                    target-url: 'https://myweatherprovider.mybluemix.net/today?zipcode={zipcode}'
          otherwise: []
          version: 1.0.0
    catch: []
consumes: 
  - application/json
